---
version: '3.4'
services:
  zeo:
    image: ged.pfwb.be/pfwb-ged:${BUILD_ID}
    volumes:
      - blobstorage:/data/blobstorage
      - filestorage:/data/filestorage
      - log:/data/log
      - type: tmpfs
        target: /var/tmp
    command: zeoserver
    healthcheck:
      disable: true
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == pfwb-ubuged6
    environment:
      - HTTP_PORT=8080
      - HOSTNAME_HOST=local
      - PROJECT_ID=plone
  instance:
    image: ged.pfwb.be/pfwb-ged:${BUILD_ID}
    volumes:
      - blobstorage:/data/blobstorage
      - log:/data/log

    deploy:
      replicas: 8
      placement:
        constraints:
          - node.hostname == pfwb-ubuged6
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.pfwb-ged-staging-login.rule=Host(`ged-staging.pfwb.be`) && Method(`Post`) && Path (`/`)"
        - "traefik.http.routers.pfwb-ged-staging-login.priority=1"
        - "traefik.http.routers.pfwb-ged-staging-login.entrypoints=web"
        - "traefik.http.services.pfwb-ged-staging-login.loadbalancer.server.port=8080"
        - "traefik.http.routers.pfwb-ged-staging-login.middlewares=add-pfwb-ged-staging-login-vhost"
        - "traefik.http.middlewares.add-pfwb-ged-staging-login-vhost.addprefix.prefix=/VirtualHostBase/https/ged-staging.pfwb.be:443/pfwbged/VirtualHostRoot/dashboard"
        - "traefik.http.routers.pfwb-ged-staging.rule=Host(`ged-staging.pfwb.be`)"
        - "traefik.http.routers.pfwb-ged-staging.priority=2"
        - "traefik.http.routers.pfwb-ged-staging.entrypoints=web"
        - "traefik.http.services.pfwb-ged-staging.loadbalancer.server.port=8080"
        - "traefik.http.routers.pfwb-ged-staging.middlewares=add-pfwb-ged-staging-vhost"
        - "traefik.http.middlewares.add-pfwb-ged-staging-vhost.addprefix.prefix=/VirtualHostBase/https/ged-staging.pfwb.be:443/pfwbged/VirtualHostRoot"
    ports:
      - 8080
    networks:
      - default
      - traefik
    environment:
      - HTTP_PORT=8080
      - ZEO_ADDRESS=zeo:8100
      - HOSTNAME_HOST=local
      - PROJECT_ID=plone
      - ROOT_URL=https://ged-staging.pfwb.be
  worker:
    image: ged.pfwb.be/pfwb-ged:${BUILD_ID}
    volumes:
      - blobstorage:/data/blobstorage
      - log:/data/log
    command: worker
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == pfwb-ubuged6
    networks:
      - default
    environment:
      - HTTP_PORT=8080
      - ZEO_ADDRESS=zeo:8100
      - HOSTNAME_HOST=local
      - PROJECT_ID=plone
      - ROOT_URL=https://ged-staging.pfwb.be
  redis:
    image: redis
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == pfwb-ubuged6
    networks:
      - default
  solr:
    image: ged.pfwb.be/pfwb-ged:${BUILD_ID}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == pfwb-ubuged6
    volumes:
      - solr:/plone/var/solr
      - log:/data/log
    command: solr-instance
    networks:
      - default
    healthcheck:
      disable: true

networks:
  traefik:
    external:
      name: traefik

volumes:
  blobstorage:
  filestorage:
  solr:
  log:
