---
version: '3.4'
services:
  zeo:
    image: docker-registry.pfwb.be/pfwb-ged:17
    volumes:
      - blobstorage:/data/blobstorage
      - filestorage:/data/filestorage
      - log:/data/log
      - type: tmpfs
        target: /var/tmp
    command: zeoserver
    healthcheck:
      disable: true
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == pfwb-ubuged6
    environment:
      - HTTP_PORT=8080
      - HOSTNAME_HOST=local
      - PROJECT_ID=plone
  instance:
    image: docker-registry.pfwb.be/pfwb-ged:${BUILD_ID}
    volumes:
      - blobstorage:/data/blobstorage
      - documentviewer:/data/documentviewer
      - log:/data/log
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
      - type: tmpfs
        target: /plone/tmp
    deploy:
      replicas: 8
      placement:
        constraints:
          - node.hostname == pfwb-ubuged6
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.pfwb-ged-staging-login.rule=Host(`ged-staging.pfwb.be`) && Method(`GET`) && Path (`/`)"
        - "traefik.http.routers.pfwb-ged-staging-login.priority=2"
        - "traefik.http.routers.pfwb-ged-staging-login.entrypoints=web"
        - "traefik.http.routers.pfwb-ged-staging-login.service=pfwb-ged-staging-login"
        - "traefik.http.services.pfwb-ged-staging-login.loadbalancer.server.port=8080"
        - "traefik.http.routers.pfwb-ged-staging-login.middlewares=add-pfwb-ged-staging-login-vhost"
        - "traefik.http.middlewares.add-pfwb-ged-staging-login-vhost.addprefix.prefix=/VirtualHostBase/https/ged-staging.pfwb.be:443/pfwbged/VirtualHostRoot/dashboard"
        - "traefik.http.routers.pfwb-ged-staging.rule=Host(`ged-staging.pfwb.be`)"
        - "traefik.http.routers.pfwb-ged-staging.priority=1"
        - "traefik.http.routers.pfwb-ged-staging.entrypoints=web"
        - "traefik.http.routers.pfwb-ged-staging.service=pfwb-ged-staging"
        - "traefik.http.services.pfwb-ged-staging.loadbalancer.server.port=8080"
        - "traefik.http.routers.pfwb-ged-staging.middlewares=add-pfwb-ged-staging-vhost"
        - "traefik.http.middlewares.add-pfwb-ged-staging-vhost.addprefix.prefix=/VirtualHostBase/https/ged-staging.pfwb.be:443/pfwbged/VirtualHostRoot"
    ports:
      - 8080
    networks:
      - default
      - traefik
    environment:
      - HTTP_PORT=8080
      - ZEO_ADDRESS=zeo:8100
      - HOSTNAME_HOST=local
      - PROJECT_ID=plone
      - ROOT_URL=https://ged-staging.pfwb.be
      - zope_i18n_allowed_languages=fr
    extra_hosts:
      - "dc1.dom.pfwb.be:172.23.3.139"
      - "dc2.dom.pfwb.be:172.23.3.159"
      - "SRV-WIN-DC02.dom.pfwb.be:10.80.1.148"
      - "SRV-WIN-DC04.dom.pfwb.be:10.80.1.125"

  instance-debug:
    image: docker-registry.pfwb.be/pfwb-ged:${BUILD_ID}
    command: sleep infinity
    healthcheck:
      disable: true
    volumes:
      - blobstorage:/data/blobstorage
      - documentviewer:/data/documentviewer
      - log:/data/log
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
      - type: tmpfs
        target: /plone/tmp
    deploy:
      replicas: 0
      placement:
        constraints:
          - node.hostname == pfwb-ubuged6
    ports:
      - 32000:8080
    networks:
      - default
    environment:
      - HTTP_PORT=8080
      - ZEO_ADDRESS=zeo:8100
      - HOSTNAME_HOST=local
      - PROJECT_ID=plone
      - ROOT_URL=https://ged-staging.pfwb.be
      - zope_i18n_allowed_languages=fr
    extra_hosts:
      - "dc1.dom.pfwb.be:172.23.3.139"
      - "dc2.dom.pfwb.be:172.23.3.159"
      - "SRV-WIN-DC02.dom.pfwb.be:10.80.1.148"
      - "SRV-WIN-DC04.dom.pfwb.be:10.80.1.125"

  worker:
    image: docker-registry.pfwb.be/pfwb-ged:${BUILD_ID}
    volumes:
      - blobstorage:/data/blobstorage
      - log:/data/log
      - documentviewer:/data/documentviewer
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
      - type: tmpfs
        target: /plone/tmp
    command: worker
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == pfwb-ubuged6
    networks:
      - default
    environment:
      - HTTP_PORT=8080
      - ZEO_ADDRESS=zeo:8100
      - HOSTNAME_HOST=local
      - PROJECT_ID=plone
      - ROOT_URL=https://ged-staging.pfwb.be
      - zope_i18n_allowed_languages=fr
    extra_hosts:
      - "dc1.dom.pfwb.be:172.23.3.139"
      - "dc2.dom.pfwb.be:172.23.3.159"
      - "SRV-WIN-DC02.dom.pfwb.be:10.80.1.148"
      - "SRV-WIN-DC04.dom.pfwb.be:10.80.1.125"
  redis:
    image: redis
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == pfwb-ubuged6
    networks:
      - default
  solr:
    image: docker-registry.pfwb.be/pfwb-ged:${BUILD_ID}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == pfwb-ubuged6
    volumes:
      - solr:/data/solr
      - blobstorage:/data/blobstorage
      - documentviewer:/data/documentviewer
      - log:/data/log
    command: solr-instance
    networks:
      - default
    healthcheck:
      disable: true

networks:
  traefik:
    external:
      name: traefik

volumes:
  blobstorage:
  filestorage:
  solr:
  log:
  documentviewer:
